- .travis.yml
- pkg/cloudprovider/kubevirt/cloud.go
- pkg/cloudprovider/kubevirt/cloud_test.go
- pkg/cloudprovider/kubevirt/instances.go
- pkg/cloudprovider/kubevirt/instances_test.go
- pkg/cloudprovider/kubevirt/loadbalancer.go
ATM KubeVirt-cloud-controller-manager accepts a kubeconfig file as cloud-config.
This patch extends the format of cloud-config to support additional configuration beyond kubeconfig.
For example, this cloud-config sets the kubeconfig and disables the loadbalancer interface.
```
kubeconfig: |
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: xxx
server: https://127.0.0.1:6443
name: kubernetes
contexts:
- context:
cluster: kubernetes
user: kubernetes-admin
namespace: shoots
name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
user:
client-certificate-data: xxx
client-key-data: xxx
loadbalancer:
enbled: false
```
> Extend cloud-config format

- pkg/cloudprovider/kubevirt/instances.go
- pkg/cloudprovider/kubevirt/instances_test.go
The node_controller of the cloud controller will create a NodeAdress for
the hostname reported by kubelet if it is not set. It is therefore
unnecessary to set it in the cloud provider.
> Only set hostname as NodeAddress if it is defined in the VMI spec

- pkg/cloudprovider/kubevirt/zones.go
This PR adds code to consider the newer `topology` labels in the zone controller, in addition to the older `failure-domain` ones. According to https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/, starting in v1.17, the  `failure-domain.beta.kubernetes.io/region` label is deprecated in favor of `topology.kubernetes.io/region`, and the `failure-domain.beta.kubernetes.io/zone` label is deprecated in favor of `topology.kubernetes.io/zone`.
Since the cloud provider still vendors Kubernetes 1.16, the newer labels of the underkube nodes will be considered when determining the region and zone, but not actually added to the overkube nodes (as this is done by the vendored code). Vendoring a newer Kubernetes version is unfortunately close to impossible since …
> Consider newer topology labels in zone controller

- pkg/cloudprovider/kubevirt/loadbalancer.go
- pkg/cloudprovider/kubevirt/loadbalancer_test.go
This PR copies annotations that are on a proxied `Service` to the proxy and is required in the Gardener Kubevirt provider so that a MetalLB instance in the seed can be configured by the shoot (such as address pool selection).
/resolves #15 
cc: @stoyanr
> Copy annotations from proxied service to proxy

- .github/workflows/go.yml
- .travis.yml
It seems like Travis CI does no longer trigger any tests on new PRs or pushes.
This PR replaces the Travis CI configuration with GitHub Actions in hope that
it will work more reliable.
> Replace Travis CI with GitHub Actions

- pkg/provider/cloud.go
- pkg/provider/cloud_test.go
This PR allows to read the cloud namespace from CCM config instead of always reading it from the kubeconfig.
Fixes: #78 
Signed-off-by: Helene Durand <helene@kubermatic.com>
> Add a possibility to read namespace from CCM config

- .github/workflows/publish.yaml
After a PR is merged or main branch tagged a image should be pushed to
quay.io. This change add a github actions that do so and also add a
manual trigger to actionate from github actions menu or github CLI.
> infra: Add a gh actions to publish images

- Makefile
The alpine image does not containe the needed librarys to run non
statically linked golang binary. This change disable CGO to compile into
a statically linked one.
> make: Disable CGO

- pkg/provider/cloud.go
- pkg/provider/cloud_test.go
- pkg/provider/instances_v2.go
- pkg/provider/instances_v2_test.go
This change is done in order to let the user option not to get this info
Currently, this info located in the Nodes, therefore it require the
controller to have Node get permission (cluster scope)
There is plane in kubevirt, to addopt this info also in the vmi,
which will allow to get this info without the Get Node permission
Related issue:
https://github.com/kubevirt/cloud-provider-kubevirt/issues/89
Fixes issue https://github.com/kubevirt/cloud-provider-kubevirt/issues/94
> InstancesV2: Add option to disable getting  Region and Zone labels

- build/images/kubevirt-cloud-controller-manager/Dockerfile
@mfranczy this is the dockerfile I use to build the image localy
Do you think we can use it upstream?
fix issue: https://github.com/kubevirt/cloud-provider-kubevirt/issues/50
> Change Dockerfile base images

- build/images/kubevirt-cloud-controller-manager/Dockerfile
Use public registry `registry.access.redhat.com/ubi9/ubi-micro`
so that authentication is not required for building an image
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
> Use public registry for ubi9/ubi-micro base image

- Makefile
- build/images/kubevirt-cloud-controller-manager/Dockerfile
When doing multistage without vendor directory is good to download first
the dependencies at different layer and then compile the code, this way
if code is changes only the layer that manage the compilation will have
to be reconstructed and deps will be download only once.
> container: Storage golang deps at different layer

- kubevirtci
Occasionally, kubevirtci::prepare fails, because kubernetes
api in tenant cluster is not ready by the time the function
attempts to install calico.
This commit waits for
a) kubernetes api available in tenant cluster
b) calico-node daemonset to be available
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
> Wait for components deployed in kubevirtci::prepare

- kubevirtci
Kubevirtci script uses mixture of spaces and tabs for indenting.
This commit unifies the script to only use tabs, as it's used in
majority of cases.
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
> Unify indenting in kubevirtci to use tabs

- config/configmap/cloud-config
- config/kubevirtci/kustomization.yaml
- config/rbac/kccm_role.yaml
- config/rbac/kccm_role_binding.yaml
- config/rbac/kustomization.yaml
- pkg/provider/cloud.go
If the cloud-config is missing the "kubeconfig" field use the InCluster
config to access infra.
> Fallback to in cluster kubeconfig

- config/manager/manager.yaml
Since we're running the kccm on the infra cluster, the volumeMounts
removed in this commit are now mounted from the infra cluster
nodes. But there should be no reason for mounting these certs.
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>
> config,manager.yaml: remove volumeMounts for k8s certs

- README.md
- pkg/provider/instances_v2.go
- pkg/provider/loadbalancer.go
- pkg/provider/loadbalancer_test.go
- test/e2e/cloud_provider_kubevirt/load_balancer_test.go
Change LoadBalancer use existing labels on VMI instead of setting new
> Load balancer selector changes

- config/base/kustomization.yaml
- config/overlays/default/kustomization.yaml
- config/overlays/isolated/kustomization.yaml
When kustomize generate the secrets and configmaps it prepend a suffix so they are keep after deploy, this is not needed for kccm. This change add a flag to disable that kustomize feature.
> kustomize: Remove generated secret/cm suffix

- config/isolated/kustomization.yaml
When using kustomize isolated overlay the reference to kube-system is not needed, this change remove that at the isolated kustomization file.
> kustomize: Remove ref to kube-system isolated RBAC

- config/isolated/kustomization.yaml
- config/rbac/kccm_role.yaml
Nodes is not needed for isolated overlay since the node sync feature is deactivated at cloud-config.
This change also reduce the verbos for pods since update is not needed.
> kustomize, isolated: Remove nodes RBAC

- pkg/provider/loadbalancer_test.go
Fixes: #91 
Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>
> rewrite unit-tests with ginkgo

- pkg/provider/cloud.go
- pkg/provider/loadbalancer.go
- pkg/provider/loadbalancer_test.go
Using the cloud config, we should be able to add unique labels to the infra cluster load balancers which can help associating the LBs with cluster related resources (Like hypershift HostedClusters and NodePools)
> Add id custom labels to infra Load balancers

- README.md
- config/default/cloud-config
- config/isolated/cloud-config
- pkg/provider/cloud.go
- pkg/provider/cloud_test.go
- pkg/provider/loadbalancer.go
- pkg/provider/loadbalancer_test.go
Add a polling timeout at infra service creation to fail if services do not receive IPs after a period of time.
This will fail in cases where the lb provider has no more IPs or if there are failures like AWS not supporting multi protocol.
If the loop is not broken kccm is stuck and no more services will be created.
Closes: https://issues.redhat.com/browse/OCPBUGS-15055
> lb: Add creation polling timeout

- pkg/provider/instances_v2.go
- pkg/provider/instances_v2_test.go
We've seen instances where the vmi.Status.Interfaces list temporarily clears and stops reporting the default instance IP. This occurs when the qemu guest agent can not be contacted, such as during an internal soft reboot. It also occurs for reasons we do not 100% understand yet.
Since we know this vmi.Status.Interfaces field is dependent on the qemu guest agent, there will be times where the agent is unavailable. To smooth over those time periods, cloud-provider-kubevirt now only reports IP changes on the node when we're certain the IP has actually changed, and does not clear out the internal IP when no default ip is reported on the vmi status.
> Only set internal ip on node when default IP is present on VMI

- pkg/provider/cloud.go
- pkg/provider/loadbalancer.go
- pkg/provider/loadbalancer_test.go
**What this PR does / why we need it**:
For kubevirt virtualmachines without pod networking with just multus secondary networks the generated endpointslices from the service selector are of no use since they are point to the virt-launcher pod that do not point to any VM.
This change add a flag to the lb config so users can skip the lb service selector generation and create their own endpointslices pointing to the secondary network IPs.
```release-note
Add selectorless load balancer config flag
```
> lb: Add selectorless config flag

- build/images/kubevirt-cloud-controller-manager/Dockerfile
**What this PR does / why we need it**:
The podman instance in CI no longer accepts short images names.
Update the kubevirt-cloud-controller-manager Containerfile to use the full name for the golang builder image.
This allows the e2e lane to pass again[1]
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cloud-provider-kubevirt/332/pull-kubevirt-cloud-provider-kubevirt-e2e/1841490243212021760
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**Special notes for your reviewer**:
**Checklist**
This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.
**Release note**: …
> Use full image name for golang builder container image

- pkg/controller/kubevirteps/kubevirteps_controller.go
- pkg/controller/kubevirteps/kubevirteps_controller_test.go
This PR introduces the following key changes to the `kubevirteps` controller:
- **Added infra EndpointSlice Informer**: The controller now watches for `EndpointSlice` events (add, update, delete) in the infra cluster.
- **Reconciliation on EndpointSlice deletion**: The controller detects when an infra `EndpointSlice` is deleted and automatically re-queues the associated Service for reconciliation.
- **Refactored `reconcile` logic**: Improved the `getInfraServiceForEPS` function to map `EndpointSlices` back to their associated infra `Services` using labels.
- **Enhanced tests**:
- Verified restoration of infra `EndpointSlice` after manual deletion.
- Ensured correct handling of Services with multiple unique ports.
- Covered scenarios for updating `EndpointSlices` when associated `Services` …
> Add support for reconciling and restoring infra EndpointSlices

- pkg/controller/kubevirteps/kubevirteps_controller.go
- pkg/controller/kubevirteps/kubevirteps_controller_test.go
This PR resolves an issue where `EndpointPort` fields in `reconcileByAddressType` pointed to the same memory address across iterations, causing duplicate values in `desiredPorts`. The fix ensures unique memory addresses are used for each port by creating separate variables for `Name`, `Protocol`, and `TargetPort` on each loop iteration.
```
E1205 10:40:39.191901       1 kubevirteps_controller.go:535] Failed to create EndpointSlice  in namespace tenant-freemont: EndpointSlice.discovery.k8s.io "a1a08215a57704dc8a52248f3121d731m969n" is invalid: [ports[1].name: Duplicate value: "serve", ports[2].name: Duplicate value: "serve", ports[3].name: Duplicate value: "serve", ports[4].name: Duplicate value: "serve"]
```
>  Fix: Correctly assign unique memory addresses for EndpointSlice ports in reconcileByAddressType
